SFDCInvoice/Project_Expenses/src/objects/Expan__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <label>Expense</label>
        <referenceTo>Expance__c</referenceTo>
        <relationshipLabel>Expense-Member-Details</relationshipLabel>
        <relationshipName>Expense_Member_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Expense-Member-Details</relationshipLabel>
        <relationshipName>Expense_Member_Details</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>money_contributed__c</fullName>
        <label>money contributed</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Expense-Member-Detail</label>
    <nameField>
        <displayFormat>exp-mem-{0000000}</displayFormat>
        <label>Expan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense-Member-Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCInvoice/Project_Expenses/src/objects/Expance__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCInvoice/Project_Expenses/src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCInvoice/Project_Expenses/src/classes/ExpenseTest.cls
@isTest
public class ExpenseTest {     

 public testMethod static void myTest(){
      
        Expance__c expense = new Expance__c();
        expense.Amount__c=1000;
        insert expense;
        Member__c member = new Member__c();
        member.Email__c='abc@abc.com';
        insert member;
        Expan__c expmem = new Expan__c();
        expmem.Member__c=member.Id;
        expmem.Expense__c=expense.Id;
        expmem.money_contributed__c=100;
        insert expmem;
        
       ExpanceDetails expExt = new ExpanceDetails(new ApexPages.StandardController(expense));
        
      
}
}