SFDCInvoice/Project_Expenses/src/objects/Expan__c.object
<CustomObject>
    <fields>
        <fullName>Expense__c</fullName>
        <label>Expense</label>
        <referenceTo>Expance__c</referenceTo>
        <relationshipLabel>Expense-Member-Details</relationshipLabel>
        <relationshipName>Expense_Member_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Expense-Member-Details</relationshipLabel>
        <relationshipName>Expense_Member_Details</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>money_contributed__c</fullName>
        <label>money contributed</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Expense-Member-Detail</label>
    <nameField>
        <displayFormat>exp-mem-{0000000}</displayFormat>
        <label>Expan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense-Member-Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCInvoice/Project_Expenses/src/objects/Expance__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>TODAY()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>remaining_money__c</fullName>
        <label>remaining money</label>
        <summarizedField>Expan__c.money_contributed__c</summarizedField>
        <summaryForeignKey>Expan__c.Expense__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCInvoice/Project_Expenses/src/objects/Member__c.object
<CustomObject>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCInvoice/Project_Expenses/src/classes/ExpanceDetails.cls
/*  extension class for Expense
Class to fetch detalis for Total Expense and member names who contributed money
*/
public class ExpanceDetails {                //class name
  public ApexPages.StandardController controller{get;set;}
  public List<Expance__c> Expance{get;set;}``
  public List<Expan__c> expMem{get;set;}
  public Expance__c expObj{get;set;}

/* Constructor */
    public ExpanceDetails(ApexPages.StandardController controller) { 
     this.controller = controller;
     expObj = (Expance__c)controller.getRecord();
     fetchRecord();
    }

/* Method to fetch details for Total amount,contributed money per member,member name and event name */ 
 
 public PageReference fetchRecord()      //method fetchRecord
{
    Expance = [select Id,Name,Amount__c,Date__c,remaining_money__c,(select Id, Name , money_contributed__c,Member__c, Member__r.name from Expense_Member_Details__r) from Expance__c where Id =: expObj.Id];
    if(!expance.isEmpty()){
        expMem = Expance[0].Expense_Member_Details__r;
    }
    return null;
    


}

}